name: Build DEB Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deb-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          PACKAGE_NAME="primo-di-tutto"
          VERSION="0.4.6"
          DEPENDENCIES="python3-dev, python3-psutil, python3-distro, python3-bs4, python3-requests, python3-pil, python3-pil.imagetk, xterm, mpg123, lolcat, wmctrl, gdebi, mousepad, appstream, pkexec | policykit-1"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev fakeroot rsync

      - name: Create directory structure
        run: |
          mkdir -p PRIMO-DEBIAN-BUILD-BOX/debian/DEBIAN
          mkdir -p PRIMO-DEBIAN-BUILD-BOX/debian/opt/$PACKAGE_NAME
          mkdir -p PRIMO-DEBIAN-BUILD-BOX/debian/usr/bin
          mkdir -p PRIMO-DEBIAN-BUILD-BOX/debian/usr/share/applications
          mkdir -p PRIMO-DEBIAN-BUILD-BOX/debian/usr/share/icons/hicolor/256x256/apps
          mkdir -p PRIMO-DEBIAN-BUILD-BOX/debian/usr/share/icons/hicolor/scalable/apps
          mkdir -p PRIMO-DEBIAN-BUILD-BOX/debian/usr/share/metainfo
          mkdir -p PRIMO-DEBIAN-BUILD-BOX/debian/usr/share/doc/$PACKAGE_NAME

      - name: Copy application files
        run: |
          rsync -av --exclude='start.sh' --exclude='.vscode' --exclude='src/__pycache__' --exclude='src/tabs/__pycache__' primo-di-tutto/ PRIMO-DEBIAN-BUILD-BOX/debian/opt/$PACKAGE_NAME
          cp PRIMO-DEBIAN-BUILD-BOX/icon/primo-di-tutto-logo.png PRIMO-DEBIAN-BUILD-BOX/debian/usr/share/icons/hicolor/256x256/apps/
          cp PRIMO-DEBIAN-BUILD-BOX/icon/primo-di-tutto-logo.svg PRIMO-DEBIAN-BUILD-BOX/debian/usr/share/icons/hicolor/scalable/apps/
          cp PRIMO-DEBIAN-BUILD-BOX/io.github.actionschnitzel.primo-di-tutto.appdata.xml PRIMO-DEBIAN-BUILD-BOX/debian/usr/share/metainfo/
          cp LICENSE PRIMO-DEBIAN-BUILD-BOX/debian/usr/share/doc/$PACKAGE_NAME/LICENSE

      - name: Create control file
        run: |
          cat > PRIMO-DEBIAN-BUILD-BOX/debian/DEBIAN/control << EOF
          Package: $PACKAGE_NAME
          Version: $VERSION
          Architecture: all
          Maintainer: Timo Westphal <pigroxtrmo@gmail.com>
          Depends: $DEPENDENCIES
          Section: misc
          Priority: optional
          Homepage: https://zestful-pigroxtrmo.wordpress.com/
          License: GPL-3.0
          Description: A system control tool for Raspberry Pi
           PiGro is a system configuration tool inspired by openSUSE's YaST
           but designed with the user-friendliness of Linux Mint in mind.
          EOF

      - name: Create DEBIAN scripts
        run: |
          cat > PRIMO-DEBIAN-BUILD-BOX/debian/DEBIAN/preinst << 'EOF'
          #!/bin/bash
          default_terminal=$(readlink -f /usr/bin/x-terminal-emulator)
          echo "$default_terminal" > /tmp/default_terminal_path
          EOF
          chmod +x PRIMO-DEBIAN-BUILD-BOX/debian/DEBIAN/preinst

          cat > PRIMO-DEBIAN-BUILD-BOX/debian/DEBIAN/postinst << 'EOF'
          #!/bin/bash
          default_terminal_path=$(cat /tmp/default_terminal_path)
          if [ ! -z "$default_terminal_path" ] && [ "$(readlink -f /usr/bin/x-terminal-emulator)" != "$default_terminal_path" ]; then
            update-alternatives --set x-terminal-emulator "$default_terminal_path"
          fi
          rm -f /tmp/default_terminal_path
          USER_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
          AUTOSTART_DIR="$USER_HOME/.config/autostart"
          mkdir -p "$AUTOSTART_DIR"
          cp /usr/share/applications/autostart/primo-di-tutto-autostart.desktop "$AUTOSTART_DIR/"
          chmod +x "$AUTOSTART_DIR/primo-di-tutto-autostart.desktop"
          EOF
          chmod +x PRIMO-DEBIAN-BUILD-BOX/debian/DEBIAN/postinst

      - name: Create .desktop file
        run: |
          cat > PRIMO-DEBIAN-BUILD-BOX/debian/usr/share/applications/primo-di-tutto.desktop << EOL
          [Desktop Entry]
          Version=2.1
          Exec=primo-di-tutto
          Name=Primo Di Tutto
          GenericName=Primo
          Encoding=UTF-8
          Terminal=false
          StartupWMClass=Primo
          Type=Application
          Categories=System
          Icon=primo-di-tutto-logo
          Path=/opt/primo-di-tutto/
          EOL

      - name: Set permissions and build DEB package
        run: |
          chmod -R 755 PRIMO-DEBIAN-BUILD-BOX/debian
          sudo chown -R root:root PRIMO-DEBIAN-BUILD-BOX/debian
          dpkg-deb --build -Zxz PRIMO-DEBIAN-BUILD-BOX/debian
          mv PRIMO-DEBIAN-BUILD-BOX/debian.deb ./primo-di-tutto-$VERSION.deb

      - name: Verify DEB package file
        run: |
          ls -la
          ls -la ./primo-di-tutto-$VERSION.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: primo-di-tutto-deb
          path: ./primo-di-tutto-$VERSION.deb
